DECLARE
    V_RUN               VARCHAR2(13):=&RUT;
    V_NROCLIENTE        CLIENTE.NRO_CLIENTE%TYPE;
    V_RUT               VARCHAR2(20);
    V_NOMBRE            VARCHAR2(60);
    V_PROFESION         VARCHAR2(60);
    V_CUMPLE            VARCHAR2(30);
    V_GIFTCARD          NUMBER(10);
    V_OBSERVACION       VARCHAR2(60);
    V_FECNAC            DATE;
    V_MONTO             NUMBER(8);
    
BEGIN
    SELECT C.NRO_CLIENTE, 
        TO_CHAR(C.NUMRUN,'09G999G999')||'-'||C.DVRUN,
        INITCAP(C.PNOMBRE||' '||C.SNOMBRE||' '||C.APPATERNO||' '||C.APMATERNO),
        PO.NOMBRE_PROF_OFIC,
        TO_CHAR(C.FECHA_NACIMIENTO,'DD "de" Month'),
        C.FECHA_NACIMIENTO
    INTO V_NROCLIENTE, V_RUT, V_NOMBRE, V_PROFESION, V_CUMPLE, V_FECNAC
    FROM CLIENTE C
    JOIN PROFESION_OFICIO PO ON C.COD_PROF_OFIC =PO.COD_PROF_OFIC
    WHERE C.NUMRUN=V_RUN;
    
    ----- OBTENEMOS EL TOTAL AHORRADO DEL CLIENTE ----
    SELECT SUM(MONTO_TOTAL_AHORRADO)
    INTO V_MONTO
    FROM PRODUCTO_INVERSION_CLIENTE
    WHERE NRO_CLIENTE=V_NROCLIENTE;
    
    ---- DETERMINAMOS SI EL CLIENTE ESTÁ DE CUMPLEAÑOS EL MES SIGUIENTE ----
    IF EXTRACT(MONTH FROM V_FECNAC)=EXTRACT(MONTH FROM SYSDATE)+1 THEN

        V_GIFTCARD:=CASE
                        WHEN V_MONTO BETWEEN 900001 AND 2000000 THEN 50000
                        WHEN V_MONTO BETWEEN 2000001 AND 5000000 THEN 100000
                        WHEN V_MONTO BETWEEN 5000001 AND 8000000 THEN 200000
                        WHEN V_MONTO BETWEEN 8000001 AND 15000000 THEN 300000
                        ELSE 0
                    END;
        V_OBSERVACION:=NULL;
    ELSE
        V_GIFTCARD:=NULL;
        V_OBSERVACION:='El cliente no está de cumpleaños en el mes procesado';
    END IF;
    
    INSERT INTO CUMPLEANNO_CLIENTE
    VALUES (V_NROCLIENTE,
            V_RUT,
            V_NOMBRE,
            V_PROFESION,
            V_CUMPLE,
            V_GIFTCARD,
            V_OBSERVACION);
END;

--- PROBAMOS EL RESULTADO -----
TRUNCATE TABLE CUMPLEANNO_CLIENTE;
SELECT * FROM CUMPLEANNO_CLIENTE;