---- CASO 1 ----
SET SERVEROUTPUT ON

VARIABLE B_ANNO VARCHAR2(4)
EXEC :B_ANNO:=&AÑO

VARIABLE B_RUT VARCHAR2(10)
EXEC :B_RUT:=&RUT

----- COMIENZA BLOQUE -----
DECLARE
    V_RUN           NUMBER(8);
    V_DV            VARCHAR2(1);
    V_NOMBRE        VARCHAR2(60);
    V_SUELDO        NUMBER(8);
    V_IDCOMUNA      NUMBER(3);
    V_PORC_NORMAL   NUMBER(3);
    V_VALOR_NORMAL  NUMBER(8);
    V_MOVIC_ADIC    NUMBER(8);
    V_TOTAL_MOVIC   NUMBER(8);

BEGIN
    SELECT NUMRUN_EMP, DVRUN_EMP, 
        PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP,
        SUELDO_BASE, ID_COMUNA
    INTO V_RUN, V_DV, V_NOMBRE, V_SUELDO, V_IDCOMUNA
    FROM EMPLEADO
    WHERE NUMRUN_EMP=:B_RUT;

    V_PORC_NORMAL:=TRUNC((V_SUELDO/100000),0);
    V_VALOR_NORMAL:=ROUND(V_SUELDO*(V_PORC_NORMAL/100),0);
    
    IF V_IDCOMUNA=117 THEN
        V_MOVIC_ADIC:=20000;
    ELSIF V_IDCOMUNA=118 THEN
        V_MOVIC_ADIC:=25000;
    ELSIF V_IDCOMUNA=119 THEN
        V_MOVIC_ADIC:=30000;
    ELSIF V_MOVIC_ADIC=120 THEN
        V_MOVIC_ADIC:=35000;
    ELSIF V_MOVIC_ADIC=121 THEN
        V_MOVIC_ADIC:=40000;
    ELSE V_MOVIC_ADIC:=0;
    END IF;
    
    V_TOTAL_MOVIC:=V_VALOR_NORMAL+V_MOVIC_ADIC;
    
    INSERT INTO PROY_MOVILIZACION
    VALUES (:B_ANNO,
            :B_RUT,
            V_DV,
            V_NOMBRE,
            V_SUELDO,
            V_PORC_NORMAL,
            V_VALOR_NORMAL,
            V_MOVIC_ADIC,
            V_TOTAL_MOVIC);

END;

/*SELECT * FROM proy_movilizacion;*/

----- CASO 2 ----
SET SERVEROUTPUT ON
VARIABLE B_RUT NUMBER
EXEC :B_RUT:=&RUT

DECLARE
    V_PRIMER_NOMBRE             VARCHAR2(20);
    V_NOMBRE                    VARCHAR2(60);
    V_DV                        VARCHAR2(1);
    V_SUELDO                    NUMBER(8);
    V_FCONTRATO                 DATE;
    V_USUARIO                   VARCHAR2(30);
    V_ANTIGUEDAD                NUMBER(3);

BEGIN
    
    /*GENERANDO EL USUARIO A PARTIR DE LOS DATOS DEL TRABAJADOR*/
    SELECT PNOMBRE_EMP,
        PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP,
        DVRUN_EMP,
        SUELDO_BASE,
        FECHA_CONTRATO
    INTO V_PRIMER_NOMBRE, V_NOMBRE, V_DV, V_SUELDO, V_FCONTRATO
    FROM EMPLEADO
    WHERE NUMRUN_EMP=:B_RUT;
    
    V_USUARIO:=SUBSTR(V_PRIMER_NOMBRE,1,3);
    V_USUARIO:=V_USUARIO||LENGTH(V_PRIMER_NOMBRE)||'*';
    V_USUARIO:=V_USUARIO||SUBSTR(V_SUELDO,-1,1)||V_DV;    
    
    V_ANTIGUEDAD:=EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM V_FCONTRATO);
    V_USUARIO:=V_USUARIO||V_ANTIGUEDAD;
    
    IF V_ANTIGUEDAD<10 THEN
        V_USUARIO:=V_USUARIO||'X';
    END IF;
    
    DBMS_OUTPUT.PUT_LINE(V_USUARIO);
    
    /*GENERAMOS LA CLAVE DEL USUARIO*/    
    
END;